name: Notify on Directory Push # ワークフローの名前

on:
  push:  # pushイベントをトリガーにする
    paths:  # 特定のパスへのpushを監視
      - 'docs/text/**' # 監視対象のディレクトリ (例: 'docs/**')

jobs:
  notify:
    runs-on: ubuntu-latest # 実行環境

    steps:
      - name: Send Notification  # 通知を送信
        uses: actions/github-script@v6 # github-scriptアクションを使用
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Slack Webhook URLをシークレットとして設定
        with:
          script: |
            const axios = require('axios');
            const payload = {
              text: `特定のディレクトリ (your_directory) に変更がpushされました！ by: ${context.actor}`,
            };
            try {
              const response = await axios.post(process.env.SLACK_WEBHOOK_URL, payload);
              console.log('Slack notification sent successfully!');
            } catch (error) {
              console.error('Failed to send Slack notification:', error);
            }